from selenium.webdriver.common.by import By

class MainPageLocators:

    CONSTRUCTOR_SECTION = (By.XPATH, "//nav/ul/li[1]/a/p")
    LENTA_SECTION = (By.XPATH, "//nav/ul/li[2]/a/p")
    BURGER_INSCRIPTION = (By.XPATH, "//div/main/section[1]/h1")
    LENTA_INSCRIPTION = (By.XPATH, "//div/main/section[2]/h1")
    INGREDIENT_ICON = (By.XPATH, "//section[1]/div[2]/ul[1]/a[1]/img")
    INGREDIENTS_POPUP = (By.XPATH,"//div/section[1]/div[1]/div")
    CLOSE_POPUP_BUTTON = (By.XPATH, ".//div/section[1]/div[1]/button")
    DRAG_FROM_SAUSE = (By.XPATH, ".//div/main/section[1]/div[2]/ul[2]/a[2]/img")
    DROP_TO_CONSTRUCOR = (By.XPATH, ".//div/main/section[2]/ul")
    COUNTER = (By.XPATH,"//div/main/section[1]/div[2]/ul[2]/a[2]/div[1]/p")
    USER_ACC_BUTTON = (By.XPATH,".//div/header/nav/a/p")
    EMAIL_FIELD = (By.XPATH,".//div/main/div/form/fieldset[1]/div/div/input")
    PASSWORD_FIELD = (By.XPATH,".//div/main/div/form/fieldset[2]/div/div/input")
    ENTER_BUTTON = (By.XPATH,".//div/main/div/form/button")
    ORDER_BUTTON = (By.XPATH,".//div/main/section[2]/div/button")
    BUN_ICON = (By.XPATH, ".//div/main/section[1]/div[2]/ul[1]/a[1]/img")
    SAUCE_ICON = (By.XPATH, ".//div/main/section[1]/div[2]/ul[2]/a[2]/img")
    FILLING_ICON = (By.XPATH, ".//div/main/section[1]/div[2]/ul[3]/a[3]/img")
    ALL_TIME_ORDER_COUNTER = (By.XPATH, "//div/section/div[1]/div/h2") 
    ALL_TIME_ORDER_COUNTER_ON_LENTA_PAGE = (By.XPATH, ".//div/main/div/div/div/div[2]/p[2]")    
    TODAY_ORDER_COUNTER = (By.XPATH, ".//div[3]/p[2]")
    POPUP_COUNTER = (By.XPATH, "//div/section/div[1]/div/h2")
    ORDER_POPUP_CLOSE_BUTTON = (By.XPATH, ".//div/section/div[1]/button")
    CONTENT_BOX = (By.XPATH, ".//div/section/div[1]/div")
    IN_PROGRESS_TAB = (By.XPATH, ".//ul[2]/li")